[chatmail-dovecot-tls-scan]
enabled = true
backend = systemd
journalmatch = _SYSTEMD_UNIT=dovecot.service
filter = chatmail-dovecot-tls-scan
port = imap,imaps
maxretry = 1
findtime = 10m
bantime = 1h
