[Definition]
failregex = ^.*imap-login: Disconnected: Connection closed: SSL_accept\(\) failed: error:[0-9A-F]+:SSL routines::(?:unsupported protocol|wrong version number|no shared cipher|bad key share).*rip=<HOST>,.*$
ignoreregex =
